### ISSUE TITLE
Do not enable cursorline for LSP Floats

### ISSUE THREAD

**Issue by altnp** [tummetott/reticle.nvim#11]
![image](https://github.com/tummetott/reticle.nvim/assets/9112169/81352685-0eaa-4b7d-a380-6d348be27a6e)

When enabling markdown in lsp floats, the filetype is set to `markdown` not '' and the current mechanism for detecting floats is failing. 

Would it be possible to check for bt 'nofile' and ft 'markdown'?

**Comment by tummetott** [comment]
Should work now.
