### ISSUE TITLE
current line is not highlighted correctly

### ISSUE THREAD

**Issue by denstiny** [tummetott/reticle.nvim#3]
https://user-images.githubusercontent.com/57088952/229283161-542e9313-387d-4af3-8593-c9cf27e3690c.mp4

**Comment by denstiny** [comment]
I use "nvim-zh/colorful-winsep.nvim", it conflicts with the current plugin

**Comment by tummetott** [comment]
Sorry that it took me so long. Just add `NvimSeparator` to the ignore filetypes. I updated the default config. Should work now
