### ISSUE TITLE
[bug report] no `cursorline` on single buffer

### ISSUE THREAD

**Issue by kohane27** [tummetott/reticle.nvim#6]
Hello there. Hope you're doing well. It's me again.

Please see below video:

https://github.com/tummetott/reticle.nvim/assets/57322459/2799bf8c-5ffd-4503-9ebb-df3c3c9388fa

You can see my `cursorline` flashes and then gone.

Please see below config:

```lua
  {
    "tummetott/reticle.nvim",
    config = function()
      require("reticle").setup({})
    end,
  },
```

Thank you again!

**Comment by tummetott** [comment]
You must enable the `reticle.opts.on_startup.cursorline` option. See:
```vim
:help reticle.usage
```
I'm assuming your using lazy as you package manager. So just put

```lua
{
    "tummetott/reticle.nvim",
    opts = {
        on_startup = {
            cursorline = true
        },
    },
},
```

**Comment by kohane27** [comment]
Works perfectly. It was a mistake on my part. Thank you again!
