### ISSUE TITLE
Can't manage to get the plugin working

### ISSUE THREAD

**Issue by maipley** [tummetott/reticle.nvim#7]
Hi, I can't manage to get the plugin working, I currently have:
NVIM v0.9.5
NvChad 2.0
And this is a snippet from my custom/plugins.lua, and i don't really know whats wrong, it won't highlight the line nor accept any of the commands (:ReticleToggle...).

  {
    "tummetott/reticle.nvim",
    opts = {
      on_startup = {
        cursorline = true,
        cursorcolumn = false,
      },
    },
    config = function(_, opts)
      require('reticle.nvim').setup(opts)
    end,
  }
Thanks in advance!

**Comment by tummetott** [comment]
Hey. Sorry for my late reply. Do you still experience this problem? i dont use NvChad so i'm not very familiar with it's custom plugin definitions. But if you still have this problem I would investigate that for you

**Comment by tummetott** [comment]
Closed due to inactivity
