### ISSUE TITLE
Disable cursorline in vim.diagnostic.open_float?

### ISSUE THREAD

**Issue by pkazmier** [tummetott/reticle.nvim#9]
Just discovered this awesome plug-in today. It's been working great, but I did notice that a cursor line is showing the diagnostic window opened via `vim.diagnostic.open_float()`. In the image below, the first line of the diagnostic window ("Diagnostics:") has a cursor line showing:

<img width="778" alt="image" src="https://github.com/tummetott/reticle.nvim/assets/747855/ed43cfa0-2ba9-478b-8fe3-c08df4cac711">

Any suggestions on how to eliminate that? If I place the cursor in the popup and check the `filetype` it's the empty string `""`, so I'm stumped.

**Comment by tummetott** [comment]
thanks for reporting this. Should be fixed

**Comment by pkazmier** [comment]
Thanks. It works like a charm!
